#!/bin/bash
#
# Call Light first-run installer.
#
# Configure this as the first-boot script in Raspberry Pi Imager
# (after setting hostname and WiFi). It installs the newest release
# from GitHub and enables the systemd service. Internet access is
# required during installation only. See ADR 0002.
#

set -euo pipefail

REPO="https://github.com/james872/call-light.git"
TARGET="/opt/call-light"

echo "Call Light: installing system packages"

apt-get update
apt-get install -y git python3-venv python3-pip

echo "Call Light: cloning ${REPO}"

if [ ! -d "${TARGET}/.git" ]; then
    git clone "${REPO}" "${TARGET}"
fi

cd "${TARGET}"

#
# Deploy the newest release tag, never the tip of main.
#

git fetch --tags --quiet

LATEST="$(git tag --sort=-v:refname | head -n 1)"

if [ -n "${LATEST}" ]; then
    echo "Call Light: checking out release ${LATEST}"
    git checkout --quiet "${LATEST}"
fi

echo "Call Light: installing Python dependencies"

python3 -m venv venv
venv/bin/pip install --upgrade pip --quiet
venv/bin/pip install -r requirements.txt --quiet

#
# Configuration. The station identity is generated by the
# application on first start.
#

mkdir -p /etc/call-light

if [ ! -f /etc/call-light/config.yaml ]; then
    cp config/config.example.yaml /etc/call-light/config.yaml
fi

echo "Call Light: installing systemd service"

cp deploy/call-light.service /etc/systemd/system/call-light.service

systemctl daemon-reload
systemctl enable --now call-light

echo "Call Light: installation complete"
