#!/bin/bash
#
# Call Light first-run installer.
#
# Configure this as the first-boot script in Raspberry Pi Imager
# (after setting WiFi). It installs the newest release
# from GitHub and enables the systemd service. Internet access is
# required during installation only. See ADR 0002.
#

set -euo pipefail

REPO="https://github.com/james872/call-light.git"
TARGET="/opt/call-light"

set_default_hostname() {
    local interface="wlan0"
    local mac_file="/sys/class/net/${interface}/address"
    local mac
    local suffix
    local hostname

    if [ ! -r "${mac_file}" ]; then
        echo "Call Light: Wi-Fi interface ${interface} was not found." >&2
        exit 1
    fi

    mac="$(tr -d ':' < "${mac_file}")"

    if [[ ! "${mac}" =~ ^[[:xdigit:]]{12}$ ]]; then
        echo "Call Light: invalid MAC address for ${interface}: ${mac}" >&2
        exit 1
    fi

    suffix="${mac: -6}"
    hostname="call-${suffix,,}"

    # The marker prevents a re-run from overwriting a name chosen in the UI.
    if [ -e /etc/call-light/initial-hostname ]; then
        return
    fi

    echo "Call Light: setting initial hostname to ${hostname}"

    if ! hostnamectl set-hostname "${hostname}"; then
        printf '%s\n' "${hostname}" > /etc/hostname
        hostname "${hostname}"
    fi

    printf '%s\n' "${hostname}" > /etc/call-light/initial-hostname
}

echo "Call Light: installing system packages"

apt-get update
# gpiozero needs a pin factory to access the physical header.  Raspberry Pi OS
# supplies lgpio as a system package, so the virtual environment below is
# deliberately allowed to see system site packages.
apt-get install -y git python3-venv python3-pip python3-lgpio dnsmasq-base

echo "Call Light: cloning ${REPO}"

if [ ! -d "${TARGET}/.git" ]; then
    git clone "${REPO}" "${TARGET}"
fi

cd "${TARGET}"

#
# Deploy the newest release tag, never the tip of main.
#

git fetch --tags --quiet

LATEST="$(git tag --sort=-v:refname | head -n 1)"

if [ -n "${LATEST}" ]; then
    echo "Call Light: checking out release ${LATEST}"
    git checkout --quiet "${LATEST}"
fi

echo "Call Light: installing Python dependencies"

python3 -m venv --system-site-packages venv
venv/bin/pip install --upgrade pip --retries 10 --timeout 60
venv/bin/pip install -r requirements.txt --prefer-binary --retries 10 --timeout 60

#
# Configuration. The station identity is generated by the
# application on first start.
#

mkdir -p /etc/call-light

set_default_hostname

if [ ! -f /etc/call-light/config.yaml ]; then
    cp config/config.example.yaml /etc/call-light/config.yaml
fi

echo "Call Light: installing systemd service"

cp deploy/call-light.service /etc/systemd/system/call-light.service

systemctl daemon-reload
systemctl enable --now call-light

echo "Call Light: installation complete"
